spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      uri: mongodb+srv://amitanshusa2003:AB8GBHoAThFDkxlb@cluster0.ndmlqhp.mongodb.net/journaldb?retryWrites=true&w=majority&tls=true
      auto-index-creation: true

  server:
    port: 8081
    servlet:
      context-path: /journal


